theme = "awesome-identity"
baseURL = "https://www.szalimben.dev"
title = "Saúl Zalimben - Software Engineer"

# Content without language indicator will default to this language
defaultContentLanguage = "en"
# Make .Summary and .WordCount behave correctly for CJK languages
hasCJKLanguage = true
PygmentsCodeFences = true
# Enable to turn relative URLs into absolute
canonifyURLs = true
# Do not convert the url/path to lowercase
disablePathToLower = false
# Enable Emoji emoticons support for page content
enableEmoji = true
# Update the `Lastmod` parameter for each page using the last git commit date for that content file
enableGitInfo = true
# Enable generation of `robots.txt` file
enableRobotsTXT = true

## Meta Configurations (HTTP Meta tags & OpenGraph)
[params.meta]
  description = "Software Engineer at Software Natura."
  keywords = "zalimben, szalimben, backend, engineer, developer"
  images = [
    "/images/profile.jpg"
  ]

## Profile Configurations
[params.profile]
  portrait = "/images/profile.jpg"
  firstname = "Saúl"
  lastname = "Zalimben"
  title = "Software Engineer"
  bio = """Current Senior Software Engineer at [**Software Natura**](https://swnat.com/).

  6+ years experience specializing in fullstack software development, mainly backend development.

  Experienced in creating high-quality code considering the best coding practices, architectural patterns and performance, and leading small development teams.

  Interested in devising a better problem-solving method for challenging tasks, and learning new technologies and tools if the need arises.
  """

## Contacts Configurations
[params.contacts]
  email = "szalimben93@gmail.com"
  github = "zalimben"
  twitter = "szalimben"
  linkedin = "szalimben"
  devto = "szalimben"
  researchgate = "Saul-Zalimben"

## Actions Configurations
##[[params.actions]]
##  name = "Review My CV"
##  url = "https://raw.githubusercontent.com/Zalimben/Awesome-CV/master/examples/cv.pdf"
##[[params.actions]]
##  name = "Ask Me Anything"
##  url = "https://github.com/Zalimben/ama"
##[[params.actions]]
##  name = "Buy Me a Coffee"
##  url = "https://buymeacoff.ee/Zalimben"

## Footer Configurations
[params.footer]
  copyright = "2021 Saúl Zalimben. [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)."
  poweredBy = true
